# register-cron-output-watchdog.ps1
#
# Deploys the silent-cron-failure watchdog as a Windows Scheduled Task.
#
# Why a registrar and not just the XML: Task Scheduler rejects an empty <UserId>
# and this repo is a public fork, so the machine's user SID must not be versioned.
# hermes-cron-output-watchdog-task.xml is therefore a TEMPLATE carrying the
# __USER_SID__ token; this script resolves the CURRENT user's SID and substitutes
# it, which also makes the deployment reproduce on any machine.
#
# DEFAULTS TO A DRY RUN. Nothing is written or registered without -Apply.
#
# Usage:
#   .\register-cron-output-watchdog.ps1            # dry run: show what would happen
#   .\register-cron-output-watchdog.ps1 -Apply     # write launcher + register task

param(
    [string]$TaskName = "Hermes-CronOutput-Watchdog",
    [string]$TemplatePath = "$PSScriptRoot\hermes-cron-output-watchdog-task.xml",
    [string]$LauncherDir = "C:\ProgramData\claude-hidden-launchers",
    [int]$IntervalMinutes = 30,
    # Start minute of the cadence. :11/:41 keeps this off :07/:37, used by the
    # review / MCP / status-collector watchdogs.
    [int]$StartMinute = 11,
    [switch]$Apply
)

$ErrorActionPreference = "Stop"
$Invariant = [Globalization.CultureInfo]::InvariantCulture

function Step { param([string]$Text) Write-Host "  $Text" }

Write-Host "=== register $TaskName ==="
Write-Host ("  mode: " + $(if ($Apply) { "APPLY" } else { "DRY RUN (pass -Apply to register)" }))
Write-Host ""

# --- 1. template present ---
if (-not (Test-Path $TemplatePath)) { throw "Template not found: $TemplatePath" }
$xml = Get-Content -Path $TemplatePath -Raw
Step "template   : $TemplatePath"

# --- 2. resolve the current user's SID and substitute the token ---
$sid = [Security.Principal.WindowsIdentity]::GetCurrent().User.Value
if ($xml -notmatch "__USER_SID__") { throw "Template carries no __USER_SID__ token - refusing to guess a principal." }
$xml = $xml -replace "__USER_SID__", $sid
$account = (New-Object Security.Principal.SecurityIdentifier($sid)).Translate([Security.Principal.NTAccount]).Value
Step "principal  : $sid ($account)"

# --- 3. validate before touching anything ---
try { [xml]$parsed = $xml } catch { throw "Substituted XML is malformed: $($_.Exception.Message)" }
Step "xml        : well-formed"

$launcher = Join-Path $LauncherDir "$TaskName.vbs"
$script = Join-Path $PSScriptRoot "hermes-cron-output-watchdog.ps1"
foreach ($p in @($script)) {
    if (-not (Test-Path $p)) { throw "Referenced script missing: $p" }
    Step "script     : OK $p"
}

# Advance to the next future occurrence of the off-minute, stepping by the interval.
# Do NOT just roll to tomorrow: with StartMinute=11 and now=10:42, today's 00:11 is
# past, and "+1 day" would make the first fire tomorrow 00:11 -- silently delaying
# the organ by ~13h. Stepping by the interval lands on 11:11 today.
$now = Get-Date
$triggerStart = $now.Date.AddMinutes($StartMinute)
while ($triggerStart -le $now) { $triggerStart = $triggerStart.AddMinutes($IntervalMinutes) }
$boundary = $triggerStart.ToString("yyyy-MM-ddTHH:mm:ssK", $Invariant)
# The schedule is owned HERE, not by the template: substituting only the SID would
# make this script print a cadence it did not actually register. Scope the interval
# replacement to the trigger's <Repetition> block - an unscoped <Interval> pattern
# would also rewrite RestartOnFailure's interval.
# MatchEvaluator rather than a replacement string: `-replace` with "`$1..." emits a
# LITERAL `$1` (measured), producing <StartBoundary>$12026-... and a Task Scheduler
# rejection: "valeur incorrectement formatée ou hors limites (34,19):TimeTrigger".
$xml = [regex]::Replace($xml, '(<StartBoundary>)[^<]*(</StartBoundary>)', {
    param($m) $m.Groups[1].Value + $boundary + $m.Groups[2].Value
})
$xml = [regex]::Replace($xml, '(<Repetition>\s*<Interval>)[^<]*(</Interval>)', {
    param($m) $m.Groups[1].Value + "PT${IntervalMinutes}M" + $m.Groups[2].Value
})
Step "trigger    : first $boundary, then every ${IntervalMinutes}m"
Step "action     : wscript.exe //B //Nologo `"$launcher`""

# --- 4. the hidden launcher (SW_HIDE, so no console ever flashes) ---
if (Test-Path $launcher) {
    Step "launcher   : exists, left untouched"
} elseif ($Apply) {
    if (-not (Test-Path $LauncherDir)) { New-Item -ItemType Directory -Path $LauncherDir -Force | Out-Null }
    # Run(cmd, 0, True) puts SW_HIDE in the CreateProcess STARTUPINFO; -WindowStyle
    # Hidden would only apply AFTER PowerShell has already shown its console.
    $vbs = @"
' Deploys $TaskName -- generated by register-cron-output-watchdog.ps1
' Objet : lancer la commande sans jamais afficher de console.
Option Explicit
Dim sh, rc
Set sh = CreateObject("WScript.Shell")
rc = sh.Run("""powershell.exe"" -ExecutionPolicy Bypass -NoProfile -File ""$script""", 0, True)
WScript.Quit rc
"@
    [System.IO.File]::WriteAllText($launcher, $vbs, [System.Text.UTF8Encoding]::new($false))
    Step "launcher   : WRITTEN $launcher"
} else {
    Step "launcher   : MISSING (would be written to $launcher)"
}

# --- 5. register ---
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) { Step "task       : already exists (id=$($existing.TaskPath)) - Apply would overwrite it" }
else { Step "task       : absent" }

if (-not $Apply) {
    Write-Host ""
    Write-Host "=== DRY RUN - nothing written, nothing registered ==="
    exit 0
}

if (-not (Test-Path $launcher)) { throw "Launcher missing after write step: $launcher" }
Register-ScheduledTask -TaskName $TaskName -Xml $xml -Force | Out-Null
$t = Get-ScheduledTask -TaskName $TaskName
$i = Get-ScheduledTaskInfo -TaskName $TaskName
Write-Host ""
Write-Host "=== REGISTERED ==="
Write-Host ("  state     : " + $t.State)
Write-Host ("  principal : " + $t.Principal.UserId + " | " + $t.Principal.LogonType + " | " + $t.Principal.RunLevel)
Write-Host ("  next run  : " + $i.NextRunTime)
